function DH_Transform = fk_3001(theta1,theta2,theta3,theta4)
%FK_3001
%    DH_Transform = FK_3001(THETA1,THETA2,THETA3,THETA4)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    01-Oct-2025 11:14:59

t2 = sqrt(2.65e+2);
t3 = (theta1.*pi)./1.8e+2;
t4 = (theta4.*pi)./1.8e+2;
t9 = theta3+7.938034472384487e+1;
t10 = theta2-7.938034472384487e+1;
t5 = cos(t3);
t6 = cos(t4);
t7 = sin(t3);
t8 = sin(t4);
t11 = (t9.*pi)./1.8e+2;
t12 = (t10.*pi)./1.8e+2;
t13 = cos(t11);
t14 = sin(t11);
t15 = cos(t12);
t16 = sin(t12);
t17 = t13.*t15;
t18 = t14.*t15;
t19 = t13.*t16;
t20 = t14.*t16;
t21 = -t20;
t22 = t5.*t17;
t23 = t7.*t17;
t24 = t5.*t18;
t25 = t5.*t19;
t26 = t7.*t18;
t27 = t7.*t19;
t28 = t5.*t20;
t29 = t7.*t20;
t32 = t18+t19;
t30 = t5.*t21;
t31 = t7.*t21;
t33 = t17+t21;
t34 = t24+t25;
t35 = t26+t27;
t36 = t22+t30;
t37 = t23+t31;
DH_Transform = reshape([t6.*t36-t8.*t34,t6.*t37-t8.*t35,-t6.*t32-t8.*t33,0.0,-t6.*t34-t8.*t36,-t6.*t35-t8.*t37,-t6.*t33+t8.*t32,0.0,-t7,t5,0.0,0.0,t22.*1.24e+2-t28.*1.24e+2+t6.*t36.*(6.67e+2./5.0)-t8.*t34.*(6.67e+2./5.0)+t2.*t5.*t15.*8.0,t23.*1.24e+2-t29.*1.24e+2+t6.*t37.*(6.67e+2./5.0)-t8.*t35.*(6.67e+2./5.0)+t2.*t7.*t15.*8.0,t32.*-1.24e+2-t2.*t16.*8.0-t6.*t32.*(6.67e+2./5.0)-t8.*t33.*(6.67e+2./5.0)+9.6326e+1,1.0],[4,4]);
end
