function robot_jac = dk_3001(theta1,theta2,theta3,theta4)
%DK_3001
%    ROBOT_JAC = DK_3001(THETA1,THETA2,THETA3,THETA4)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    01-Oct-2025 11:53:43

t2 = theta2+theta3+theta4;
t3 = (theta1.*pi)./1.8e+2;
t4 = (theta2.*pi)./1.8e+2;
t5 = (theta3.*pi)./1.8e+2;
t6 = (theta4.*pi)./1.8e+2;
t7 = cos(t3);
t8 = cos(t4);
t9 = cos(t5);
t10 = cos(t6);
t11 = sin(t3);
t12 = sin(t4);
t13 = sin(t5);
t14 = sin(t6);
t15 = t9.*1.24e+2;
t16 = t12.*1.28e+2;
t17 = t10.*(6.67e+2./5.0);
t18 = t15+t16+t17;
robot_jac = reshape([t11.*t18.*pi.*(-1.0./1.8e+2),(t7.*t18.*pi)./1.8e+2,0.0,(t2.*t7.*pi)./1.8e+2,t2.*t11.*pi.*(-1.0./1.8e+2),1.0,t7.*t8.*pi.*(3.2e+1./4.5e+1),t8.*t11.*pi.*(3.2e+1./4.5e+1),t12.*pi.*(-3.2e+1./4.5e+1),t11,t7,0.0,t7.*t13.*pi.*(-3.1e+1./4.5e+1),t11.*t13.*pi.*(-3.1e+1./4.5e+1),t9.*pi.*(-3.1e+1./4.5e+1),t11,t7,0.0,t7.*t14.*pi.*(-6.67e+2./9.0e+2),t11.*t14.*pi.*(-6.67e+2./9.0e+2),t10.*pi.*(-6.67e+2./9.0e+2),t11,t7,0.0],[6,4]);
end
